version: '3.3'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: appContainer
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: nginxContainer
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: mysqlContainer
    image: mysql:8.0
    volumes:
      - ../:/var/www
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306